[package]
name = "nsv_rust_ext"
version = "0.1.0"
edition = "2021"

[lib]
name = "nsv_rust_ext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
nsv = "0.0.3"
